/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cvc4.app;

import static cvc4.app.MessageUtils.getMessage;
import static cvc4.utilities.StringUtils.join;
import static cvc4.utilities.StringUtils.split;

import cvc4.list.LinkedList;
import org.apache.commons.text.WordUtils;

public class App
{
  public static void main(String[] args)
  {
    LinkedList tokens;
    tokens = split(getMessage());
    String result = join(tokens);
    System.out.println(WordUtils.capitalize(result));
  }
}
