/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc4_Term */

#ifndef _Included_cvc4_Term
#define _Included_cvc4_Term
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc4_Term
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc4_Term_toString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
