/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc4_Sort */

#ifndef _Included_cvc4_Sort
#define _Included_cvc4_Sort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc4_Sort
 * Method:    deleteSort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cvc4_Sort_deleteSort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cvc4_Sort
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc4_Sort_toString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
