/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc_Solver */

#ifndef _Included_cvc_Solver
#define _Included_cvc_Solver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc_Solver
 * Method:    newSolver
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_newSolver
  (JNIEnv *, jobject);

/*
 * Class:     cvc_Solver
 * Method:    deleteSolver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cvc_Solver_deleteSolver
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cvc_Solver
 * Method:    setLogic
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cvc_Solver_setLogic
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     cvc_Solver
 * Method:    getRealSort
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_getRealSort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cvc_Solver
 * Method:    getIntegerSort
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_getIntegerSort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cvc_Solver
 * Method:    mkConst
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_mkConst
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     cvc_Solver
 * Method:    mkInteger
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_mkInteger
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cvc_Solver
 * Method:    mkReal
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_mkReal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     cvc_Solver
 * Method:    mkTerm
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_mkTerm__JIJJ
  (JNIEnv *, jobject, jlong, jint, jlong, jlong);

/*
 * Class:     cvc_Solver
 * Method:    mkTerm
 * Signature: (JIJJJ)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_mkTerm__JIJJJ
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     cvc_Solver
 * Method:    checkSat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_checkSat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cvc_Solver
 * Method:    assertFormula
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_cvc_Solver_assertFormula
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     cvc_Solver
 * Method:    push
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cvc_Solver_push
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cvc_Solver
 * Method:    checkEntailed
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_checkEntailed
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     cvc_Solver
 * Method:    pop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cvc_Solver_pop
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cvc_Solver
 * Method:    mkTrue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_cvc_Solver_mkTrue
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
