/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc_Term */

#ifndef _Included_cvc_Term
#define _Included_cvc_Term
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc_Term
 * Method:    deleteTerm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cvc_Term_deleteTerm
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cvc_Term
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvc_Term_toString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
